import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
// import { ClerkProvider } from "@clerk/nextjs";

const font = Inter({
  weight: ["300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Navbar />
        <div className=" w-[95%] lg:w-[85%] mx-auto ">{children}</div>
      </body>
    </html>
  );
}
